name: Lint and Build

on:
  push:

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install -r client/requirements.txt
        python -m pip install -r server/requirements.txt

    - name: Check formatting
      if: always()
      uses: psf/black@stable
      with:
        option: "-l 120"
        src: "."

    - name: Check style
      if: always()
      run: python -m pylint server client

  build:
    name: Build
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile.server
        push: false
        tags: cgundlach13/cloud-render-server:latest
    